export enum CodeEtape {
    /**
	 * SAISIE_RAPPORT
	 */
	SAISIE_RAPPORT ='SAISIE_RAPPORT',
	
	
	/**
	 * AVIS_CHEF_DIVISION
	 */
	AVIS_CHEF_DIVISION ='AVIS_CHEF_DIVISION',

	
	/**
	 * AVIS_CHEF_DEPARTEMENT
	 */
	AVIS_CHEF_DEPARTEMENT ='AVIS_CHEF_DEPARTEMENT',
	
	
	/**
	 * AVIS_DIRECTEUR_AGENCE
	 */
	AVIS_DIRECTEUR_AGENCE ='AVIS_DIRECTEUR_AGENCE',
	
	
	/**
	 * AVIS_DIRECTEUR_SUCCURSALE
	 */
	AVIS_DIRECTEUR_SUCCURSALE ='AVIS_DIRECTEUR_SUCCURSALE',
	
	
	/**
	 * AVIS_DIRECTEUR_REGIONAL
	 */
	AVIS_DIRECTEUR_REGIONAL ='AVIS_DIRECTEUR_REGIONAL',
	
	
	/**
	 * AVIS_SOUS_DIRECTEUR_UNITE_CENTRALE
	 */
	AVIS_SOUS_DIRECTEUR_UNITE_CENTRALE ='AVIS_SOUS_DIRECTEUR_UNITE_CENTRALE',
	
	
	/**
	 * AVIS_DIRECTEUR_ADJOINT_UNITE_CENTRALE
	 */
	AVIS_DIRECTEUR_ADJOINT_UNITE_CENTRALE ='AVIS_DIRECTEUR_ADJOINT_UNITE_CENTRALE',
	
	
	/**
	 * AVIS_DIRECTEUR_UNITE_CENTRALE
	 */
	AVIS_DIRECTEUR_UNITE_CENTRALE ='AVIS_DIRECTEUR_UNITE_CENTRALE',
	
	
	/**
	 * AVIS_DIRECTION_GENERALE
	 */
	AVIS_DIRECTION_GENERALE ='AVIS_DIRECTION_GENERALE'
}
